[package]
name = "fastwebsockets-stream"
version = "0.1.1"
edition = "2024"
authors = ["Evgeniy Zakharov <eugenezakharov7@gmail.com"]
description = """
An adapter that exposes fastwebsockets::WebSocket as a Tokio AsyncRead/AsyncWrite stream.
"""
repository = "https://github.com/evgeniygem/fastwebsockets-stream"
homepage = "https://github.com/evgeniygem/fastwebsockets-stream"
documentation = "https://docs.rs/fastwebsockets-stream"
readme = "README.md"
keywords = ["websocket", "tokio", "fastwebsockets", "stream", "async"]
categories = ["asynchronous", "network-programming", "web-programming"]
license = "MIT"

[dependencies]
fastwebsockets = { version = "0.10" }
tokio = { version = "1" }
bytes = { version = "1" }
futures = { version = "0.3" }

[dev-dependencies]
fastwebsockets = { features = ["upgrade"], version = "0.10.0" }
tokio = { features = ["full"], version = "1" }
futures = "0"
bytes = "1.10.1"
http-body-util = "0.1.3"
hyper = { features = ["full"], version = "1.7.0" }
hyper-util = { features = ["full"], version = "0.1.17" }
tokio-util = { features = ["codec"], version = "0.7.16" }

[[test]]
name = "binary"
path = "tests/binary.rs"

[[test]]
name = "close"
path = "tests/close.rs"

[[test]]
name = "error"
path = "tests/error.rs"

[[test]]
name = "framed"
path = "tests/framed.rs"

[[test]]
name = "ping"
path = "tests/ping.rs"

[[test]]
name = "shutdown"
path = "tests/shutdown.rs"

[[test]]
name = "text"
path = "tests/text.rs"
